const Products =
[
 {
    title: "Pullover Sweater",
    price: 85,
    description: "A description",
    images: "https://m.media-amazon.com/images/I/71BfFi76JML._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/71hD-lmIOXL._AC_SL1500_.jpg",
  },
 {
    title: "Men stripped V-neck",
    price: 109,
    description: "offcliff mens offcliff Men stripped V-neck long sleeves top -white-xl stripped V-neck long sleeves top",
    id: 2,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/719ksZQsaPL._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/71cc4QKxhXL._AC_SL1500_.jpg",
  },
 {
    title: "Pullover Sweatshirt",
    price: 180,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 3,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/716vc-jFIqS._AC_SL1406_.jpg",
    image1: "https://m.media-amazon.com/images/I/71g+5NDfs4S._AC_SL1408_.jpg",
  },
 {
    title: "Zip Up Hoodie ",
    price: 200,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 4,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/6194+JsrNcL._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/31Fwi2p3BRL._AC_.jpg",
  },
 {
    title: "Pullover Sweater",
    price: 168,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 5,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/71C8aakr+-L._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/719c17rk76L._AC_SL1500_.jpg",
  },
 {
    title: "Sweetshirt long sleeves",
    price: 205,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 6,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/514gUwqSaeL._AC_SL1000_.jpg",
    image1: "https://m.media-amazon.com/images/I/51r1rqrtbNL._AC_SL1000_.jpg",
  },
 {
    title: "Shirt ",
    price: 55,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 7,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/514gaX9kiaS._AC_SL1000_.jpg",
    image1: "https://m.media-amazon.com/images/I/41WnQXbzTvS._AC_SL1000_.jpg",
  },
 {
    title: "Andora Mens Shirt ",
    price: 99,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 8,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/51NWK9pyrYL._AC_.jpg",
    image1: "https://m.media-amazon.com/images/I/81KiJhUcQQL._AC_SL1500_.jpg",
  },
 {
    title: "Hoodie Dark Red Zipper ",
    price: 185,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 9,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/41IgFGR0GmL._AC_.jpg",
    image1: "https://m.media-amazon.com/images/I/41GMos6X3ZL._AC_.jpg",
  },
 {
    title: "Sleeves Jacket ",
    price: 219,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 10,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/51QfqCB29rS._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/51oKLh11dVS._AC_SL1500_.jpg",
  },
 {
    title: "Bomber Jacket ",
    price: 320,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 11,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/61bSfhfzYuS._AC_SL1500_.jpg",
    image1: "https://m.media-amazon.com/images/I/519M8tFolkS._AC_SL1500_.jpg",
  },
 {
    title: "Waterproof Zipper Full Sleeves Jacket ",
    price: 450,
    description: "Off Cliff Mens Striped Elastic Trims Long Sleeves Crew Neck Cotton Pullover SWEATSHIRT",
    id: 12,
    qty: 1 ,
    images: "https://m.media-amazon.com/images/I/51hkMtTo92S._AC_SL1411_.jpg",
    image1: "https://m.media-amazon.com/images/I/51959C4OB+S._AC_SL1404_.jpg",
  },

]
// Neck Pullover Sweater


  export default Products